SEASON_SPRING = 10
SEASON_SUMMER = 20
SEASON_FALL = SEASON_AUTUMN = 30
SEASON_WINTER = 40
SEASON_WINTER_SNOW = 45
SEASON_WINTER_DEEP = 50

DREF_SIG_SEASON = 'nm/four_seasons/season'
DREF_SIG_TERRAMAX_IS_SUMMER = 'maxxxp/seasonsxp/is_summer'
DREF_SIG_TERRAMAX_IS_AUTUMN = 'maxxxp/seasonsxp/is_autumn'
DREF_SIG_TERRAMAX_IS_MID_WINTER = 'maxxxp/seasonsxp/is_mid_winter'
DREF_SIG_TERRAMAX_IS_WINTER = 'maxxxp/seasonsxp/is_winter'

TERRAMAX_DREF_SIGNATURES = (
    DREF_SIG_TERRAMAX_IS_SUMMER,
    DREF_SIG_TERRAMAX_IS_AUTUMN,
    DREF_SIG_TERRAMAX_IS_MID_WINTER,
    DREF_SIG_TERRAMAX_IS_WINTER,
)

